---

# Crear una KVM clonando un VM template Proxmox preexistente
- name: Create a KVM by cloning a pre-existing Proxmox VM template
  proxmox_kvm:
    node: "{{ pve_kvm_node }}"
    api_user: "{{ pve_kvm_api_user }}"
    api_host: "{{ pve_kvm_api_host }}"
    api_password: "{{ pve_kvm_api_password }}"
    name: "{{ pve_kvm_hostname }}"
    clone: "{{ pve_kvm_clone_vm | default (omit) }}"            # The VM source
    full: "{{ pve_kvm_full_clone | default (omit) }}"
    storage:  "{{ pve_kvm_clone_storage | default (omit) }}"    # Target storage for full clone.
    format: "{{ pve_kvm_clone_format | default (omit) }}"       # Target drive's backing file's data format. Used only with clone
    timeout: "{{ pve_kvm_timeout }}"                      # Cloning can take a while
    target: "{{ pve_kvm_clone_target }}"                        # Target node
    vmid: "{{ pve_kvm_clone_vmid | default (omit) }}"           # VM source id
    newid: "{{ pve_kvm_clone_newid | default (omit) }}"         # Clone id
  register: pve_kvm_virtualm
  delegate_to: "{{ pve_kvm_api_host }}"

...
