---

# Crear una KVM clonando un VM template Proxmox preexistente
- name: Create a KVM by cloning a pre-existing Proxmox VM template
  community.general.proxmox_kvm:
    node: "{{ pve_node }}"
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user | default(omit) }}"
    api_password: "{{ pve_api_password | default(omit) }}"
    api_token_id: "{{ pve_api_token_id | default(omit) }}"
    api_token_secret: "{{ pve_api_token_secret | default(omit) }}"
    proxmox_default_behavior: "{{ pve_kvm_proxmox_default_behavior | default('compatibility') }}"
    validate_certs: "{{ pve_kvm_validate_certs | default(omit) }}"
    name: "{{ pve_hostname }}"
    vmid: "{{ pve_kvm_clone_vmid | default(omit) }}"
    timeout: "{{ pve_kvm_timeout | default(omit) }}"
    clone: "{{ pve_kvm_clone_vm | default(omit) }}"
    snapname: "{{ pve_kvm_clone_snapname | default(omit) }}"
    full: "{{ pve_kvm_clone_full | default(omit) }}"
    storage:  "{{ pve_kvm_clone_storage | default(omit) }}"
    format: "{{ pve_kvm_clone_format | default(omit) }}"
    target: "{{ pve_kvm_clone_target | default(omit) }}"
    newid: "{{ pve_kvm_clone_newid | default(omit) }}"
  register: pve_kvm_virtual_created
  delegate_to: "{{ pve_api_host }}"

...
