---

- name: Upload Cloud-Init snippet
  template:
    src: cloud-init_snippet.yaml.j2
    dest: "/var/lib/vz/snippets/{{ proxmox_hostname }}.yaml"
  when: "{{ clone_cloud_init_snippet | length > 0 }}"
  delegate_to: "{{ api_host }}"

# Crear una KVM clonando un VM template Proxmox preexistente
- name: Create a KVM by cloning a pre-existing Proxmox VM template
  proxmox_kvm:
    node: "{{ node }}"
    api_user: "{{ api_user }}"
    api_host: "{{ api_host }}"
    api_password: "{{ api_password }}"
    name: "{{ proxmox_hostname }}"
    clone: "{{ clone_vm | default (omit) }}"            # The VM source
    full: "{{ full_clone | default (omit) }}"
    storage:  "{{ clone_storage | default (omit) }}"    # Target storage for full clone.
    format: "{{ clone_format | default (omit) }}"       # Target drive's backing file's data format. Used only with clone
    timeout: 500                                        # Cloning can take a while
    target: "{{ clone_target }}"                        # Target node
    vmid: "{{ clone_vmid | default (omit) }}"           # VM source id
    newid: "{{ clone_newid | default (omit) }}"         # Clone id
  register: virtualm
  delegate_to: "{{ api_host }}"

- name: Set Cloud-Init snippet
  command: "qm set {{ clone_newid }} --cicustom \"user=local:snippets/{{ proxmox_hostname }}.yaml\""
  when: "{{ clone_cloud_init_snippet | length > 0 }}"
  delegate_to: "{{ api_host }}"
