---
# proxmox_create_kvm: creation of a complete virtual machine in proxmox cluster
# tasks file for ansible-role-proxmox-create-kvm/

- include_tasks: dependencies.yml

- include_tasks: create_kvm.yml
  when: not clone_from_existing | bool

- include_tasks: clone_kvm.yml
  when: clone_from_existing | bool

# Mirá el número de la VM
- name: Show the ID of the VM
  debug:
    var: virtualm

# Extraer el número de VM
- name: Extract the ID of the VM
  shell: |
    set -o pipefail
    qm list | grep -w "{{ proxmox_hostname }}" | awk '{ print $1 }'
  args:
    executable: /bin/bash
  delegate_to: "{{ api_host }}"
  register: VMID
  when: virtualm is succeeded
  changed_when: false
  tags:
    - deploy
