---
# proxmox_create_kvm: creation of a complete virtual machine in proxmox cluster
# tasks file for ansible-role-proxmox-create-kvm/

- include_tasks: dependencies.yml

- include_tasks: create_kvm.yml
  when: not pve_kvm_clone_from_existing | bool

- include_tasks: clone_kvm.yml
  when: pve_kvm_clone_from_existing | bool

# Extraer el número de VM
- name: Extract the ID of the VM
  shell: |
    set -o pipefail
    qm list | grep -w "{{ pve_kvm_hostname }}" | awk '{ print $1 }'
  args:
    executable: /bin/bash
  delegate_to: "{{ pve_kvm_api_host }}"
  register: VMID
  when: pve_kvm_virtualm is succeeded
  changed_when: false

# Encender la VM
- name: Turn on the VM
  proxmox_kvm:
    node: "{{ pve_kvm_node }}"
    api_user: "{{ pve_kvm_api_user }}"
    api_host: "{{ pve_kvm_api_host }}"
    api_password: "{{ pve_kvm_api_password }}"
    vmid: "{{ pve_kvm_VMID.stdout }}"
    state: started
  delegate_to: "{{ pve_kvm_api_host }}"
  when: pve_kvm_start_after_create | bool

...
