---
# proxmox_create_kvm: creation of a complete virtual machine in porxmox cluster
# tasks file for ansible-role-proxmox-create-kvm/

# Extraer el hostname del inventory_hostname (debe ser el fqdn)
- name: Extract hostname from inventory_hostname (must be fqdn)
  set_fact:
    proxmox_hostname: "{{ inventory_hostname.split('.')[0] }}"

# Verificar si python-pip está instalado en el nodo proxmox
- name: Verify that python-pip is installed in the Proxmox node
  apt:
    name: python-pip
    state: present
  delegate_to: "{{ api_host }}"

#  Verificar si el módulo proxmoxer de python está instalado
- name: Verify if proxmoxer pip module is installed
  pip:
    name: proxmoxer
    state: present
  delegate_to: "{{ api_host }}"

- include_tasks: create_kvm.yml
  when: not clone_from_existing | bool

- include_tasks: clone_kvm.yml
  when: clone_from_existing | bool

# Mirá el número de la VM
- name: Show the ID of the VM
  debug:
    var: virtualm

# Extraer el número de VM
- name: Extract the ID of the VM
  shell: |
    set -o pipefail
    qm list | grep -w "{{ proxmox_hostname }}" | awk '{ print $1 }'
  args:
    executable: /bin/bash
  delegate_to: "{{ api_host }}"
  register: VMID
  when: virtualm is succeeded
  changed_when: false
  tags:
    - deploy

- debug:
    var: VMID
  tags:
    - deploy
